# Generated by Django 5.1.5 on 2025-03-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='full_name',
        ),
    ]
