# Generated by Django 5.1.5 on 2025-03-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_gratuated',
            field=models.BooleanField(default=True),
        ),
    ]
