# Generated by Django 5.1.5 on 2025-03-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_student_is_gratuated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_gratuated',
            new_name='is_graduated',
        ),
    ]
